# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: rekordbox.rekordbox7
PackageVersion: 7.2.3
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: nullsoft
NestedInstallerFiles:
- RelativeFilePath: Install_rekordbox_x64_7_2_3.exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Pioneer rekordbox 7.2.3
ReleaseDate: 2025-09-17
AppsAndFeaturesEntries:
- DisplayName: rekordbox 7.2.3 64bit
  Publisher: AlphaTheta
  DisplayVersion: 7.2.3.0315
  ProductCode: Pioneer rekordbox 7.2.3
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\rekordbox\rekordbox 7.2.3'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.rekordbox.com/files/20250918055307/Install_rekordbox_x64_7_2_3.zip
  InstallerSha256: 9893CED2059E6EF6BC720251C057865A1857924983F8908E6BD0D972A1C2BE70
ManifestType: installer
ManifestVersion: 1.10.0
