# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Notch.NotchLC.QuickTimeAVIPlugin
PackageVersion: 1.0.2
InstallerLocale: en-US
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /s /v"/qn /norestart"
  SilentWithProgress: /s /v"/qb /norestart"
UpgradeBehavior: install
ProductCode: '{58586834-4778-4480-AEE0-ABD169457ABC}'
ReleaseDate: 2019-06-05
AppsAndFeaturesEntries:
- DisplayName: NotchLC Codec
  Publisher: 10 BIT FX Limited
  DisplayVersion: 1.00.0002
  ProductCode: '{58586834-4778-4480-AEE0-ABD169457ABC}'
  UpgradeCode: '{C3B75404-375A-4A80-8E49-42FFAEEC4FC6}'
  InstallerType: msi
ElevationRequirement: elevationRequired
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\Notch\NotchLC'
Installers:
- Architecture: x64
  InstallerUrl: https://cloudreleases.notch.one/NotchLC_QuicktimeAVI/NotchLC_Quicktime_AVI_Plugin_1.0.0.exe
  InstallerSha256: 9E6AD55D593F157C9D725DC126C7D8D062BDF7F17D257BD84FC1F751245F5216
ManifestType: installer
ManifestVersion: 1.12.0
